name: Atualizar Azure Repos

on:
  push:
    branches:
      - main

uses: azure/appservice-deploy@v1
with:
  app_service_name: my-app-service
  branch: main
  password: ${{ secrets.AZURE_PASSWORD }}

jobs:
  sync_with_azure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Atualizar Azure Repos
        run: |
          git remote add azure https://<rln2qey6wb7gq6jhtbsexqyci3g4tii7j37kq77pahozhnu2kogq>@dev.azure.com/QualityForce/Quality%20Force%20-%20Squad138_2230/_git/Quality%20Force%20-%20Squad138_2230
          git config --global credential.helper store # Configura para armazenar as credenciais
          git fetch azure --tags # Recupera as tags do repositório remoto
          git checkout main
          git merge azure/main # Realiza o merge das alterações do repositório remoto com o branch local
          git push azure main # Envia as alterações para o repositório remoto
