name: Atualizar Azure Repos

on:
  push:
    branches:
      - main

jobs:
  sync_with_azure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2
        
      - name: Configurar Git com credenciais
        run: |
          git config --global user.email "qualityforce138@gmail.com"
          git config --global user.name "qualityforce138"

      - name: Sincronizar com Azure Repos
        uses: azure/CLI@v1
        with:
          azcliversion: 2.29.0
          inlineScript: |
            az login --username ${{ secrets.AZURE_DEVOPS_USERNAME }} --password ${{ secrets.AZURE_DEVOPS_PASSWORD }}
            git remote add azure https://QualityForce@dev.azure.com/QualityForce/Quality%20Force%20-%20Squad138_2230/_git/api-rest-booker
            git push azure main --mirror
