name: Atualizar Azure Repos

on:
  push:
    branches:
      - main

jobs:
  sync_with_azure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Atualizar Azure Repos
        run: |
          git remote add azure https://QualityForce@dev.azure.com/QualityForce/Quality%20Force%20-%20Squad138_2230/_git/Quality%20Force%20-%20Squad138_2230
          git pull azure main
          git push azure main
